### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by a-dekker** [szymor/vwordle#4]
Have you considered supporting multiple languages? I replaced the [5-8].txt files with Dutch wordlists, and this works okay. I assume Polish is a bit less suited because of all the diacritics.

If not interested, no problem, I will run my own version with custom wordlists.

**Comment by szymor** [comment]
Yeah, I considered it but I received too little funding on itch.io for this project, so I stopped to develop new features. Diacritics would be quite time-consuming, though not impossible, but I know nobody interested in playing Polish version of the game, including me, so...

Feel free to develop the game as you wish :)
